# Generated by Django 3.0.8 on 2021-01-25 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=70, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=70, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('education_level', models.CharField(blank=True, max_length=70, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('number_dependants', models.IntegerField(blank=True, null=True)),
                ('total_worth', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='staticfiles/images')),
                ('facebookId', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('android', models.BooleanField(blank=True, default=False)),
                ('ios', models.NullBooleanField(default=False)),
                ('acceptPush', models.BooleanField(default=False)),
                ('pushToken', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='companies.Department')),
                ('organization', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='companies.Organization')),
                ('role', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='companies.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_user', to=settings.AUTH_USER_MODEL, verbose_name='Account User')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_date', models.DateTimeField()),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer', to='account.AccountUser', verbose_name='About Us')),
                ('insti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField()),
                ('approval_date', models.DateTimeField()),
                ('loan_term', models.CharField(blank=True, max_length=20, null=True)),
                ('colleteral', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_client', to='account.AccountUser', verbose_name='Client')),
                ('signing_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_officer', to='account.LoanOfficer', verbose_name='Account Officer')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField()),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='account.AccountUser', verbose_name='Client')),
                ('insti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Organization')),
                ('signing_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_account_officer', to='account.LoanOfficer', verbose_name='Account Officer')),
            ],
        ),
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('statement', models.TextField(blank=True, null=True)),
                ('statement2', models.TextField(blank=True, null=True)),
                ('statement3', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isFaceBanner', models.BooleanField(default=False)),
                ('written_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to='companies.Organization', verbose_name='About Us')),
            ],
        ),
    ]
