# Generated by Django 3.0.8 on 2021-01-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='personal_email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='work_email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
