# Generated by Django 3.0.8 on 2021-01-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210126_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='registered_byuser_as',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Registra Role'),
        ),
    ]
