# Generated by Django 3.0.8 on 2021-01-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_loanapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='client_id',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='AMT_ANNUITY',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='AMT_CREDIT',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='AMT_GOODS_PRICE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='AMT_INCOME_TOTAL',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='APARTMENTS_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='APARTMENTS_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='APARTMENTS_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='BASEMENTAREA_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='BASEMENTAREA_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='BASEMENTAREA_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='CNT_CHILDREN',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='CNT_FAM_MEMBERS',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='CODE_GENDER',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='COMMONAREA_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='COMMONAREA_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='COMMONAREA_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DAYS_BIRTH',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DAYS_EMPLOYED',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DAYS_ID_PUBLISH',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DAYS_LAST_PHONE_CHANGE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DAYS_REGISTRATION',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DEF_30_CNT_SOCIAL_CIRCLE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='DEF_60_CNT_SOCIAL_CIRCLE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ELEVATORS_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ELEVATORS_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ELEVATORS_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='EMERGENCYSTATE_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ENTRANCES_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ENTRANCES_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ENTRANCES_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='EXT_SOURCE_1',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='EXT_SOURCE_2',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='EXT_SOURCE_3',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLAG_CONT_MOBILE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLAG_DOCUMENT_2',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLAG_EMAIL',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLAG_EMP_PHONE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLAG_MOBIL',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLAG_OWN_CAR',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLAG_OWN_REALTY',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLAG_PHONE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLAG_WORK_PHONE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLOORSMAX_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLOORSMAX_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLOORSMAX_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLOORSMIN_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLOORSMIN_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FLOORSMIN_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='FONDKAPREMONT_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='HOUR_APPR_PROCESS_START',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='HOUSETYPE_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LANDAREA_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LANDAREA_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LANDAREA_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LIVE_CITY_NOT_WORK_CITY',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LIVE_REGION_NOT_WORK_REGION',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LIVINGAPARTMENTS_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LIVINGAPARTMENTS_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LIVINGAPARTMENTS_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LIVINGAREA_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LIVINGAREA_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LIVINGAREA_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NAME_CONTRACT_TYPE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NAME_EDUCATION_TYPE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NAME_FAMILY_STATUS',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NAME_HOUSING_TYPE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NAME_INCOME_TYPE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NAME_TYPE_SUITE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NONLIVINGAPARTMENTS_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NONLIVINGAPARTMENTS_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NONLIVINGAPARTMENTS_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NONLIVINGAREA_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NONLIVINGAREA_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='NONLIVINGAREA_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='OBS_30_CNT_SOCIAL_CIRCLE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='OBS_60_CNT_SOCIAL_CIRCLE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='OCCUPATION_TYPE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ORGANIZATION_TYPE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='OWN_CAR_AGE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='REGION_POPULATION_RELATIVE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='REGION_RATING_CLIENT',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='REGION_RATING_CLIENT_W_CITY',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='REG_CITY_NOT_LIVE_CITY',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='REG_CITY_NOT_WORK_CITY',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='REG_REGION_NOT_LIVE_REGION',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='REG_REGION_NOT_WORK_REGION',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='SK_ID_CURR',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='TARGET',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='TOTALAREA_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='WALLSMATERIAL_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='WEEKDAY_APPR_PROCESS_START',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='YEARS_BEGINEXPLUATATION_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='YEARS_BEGINEXPLUATATION_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='YEARS_BEGINEXPLUATATION_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='YEARS_BUILD_AVG',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='YEARS_BUILD_MEDI',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='YEARS_BUILD_MODE',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
