# Generated by Django 3.0.8 on 2021-01-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20210127_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='AMT_GOODS_PRICE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='CNT_CHILDREN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='CNT_FAM_MEMBERS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='DAYS_BIRTH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='DAYS_EMPLOYED',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='DAYS_ID_PUBLISH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='DAYS_LAST_PHONE_CHANGE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='DAYS_REGISTRATION',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='DEF_30_CNT_SOCIAL_CIRCLE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='DEF_60_CNT_SOCIAL_CIRCLE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='FLAG_CONT_MOBILE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='FLAG_DOCUMENT_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='FLAG_EMAIL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='FLAG_EMP_PHONE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='FLAG_MOBIL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='FLAG_PHONE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='FLAG_WORK_PHONE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='HOUR_APPR_PROCESS_START',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='LIVE_CITY_NOT_WORK_CITY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='LIVE_REGION_NOT_WORK_REGION',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='OBS_30_CNT_SOCIAL_CIRCLE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='OBS_60_CNT_SOCIAL_CIRCLE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='OWN_CAR_AGE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='REGION_RATING_CLIENT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='REGION_RATING_CLIENT_W_CITY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='REG_CITY_NOT_LIVE_CITY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='REG_CITY_NOT_WORK_CITY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='REG_REGION_NOT_LIVE_REGION',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='REG_REGION_NOT_WORK_REGION',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='SK_ID_CURR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='TARGET',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
