# Generated by Django 3.0.8 on 2021-01-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_loan_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_history',
            name='DEF_30_CNT_SOCIAL_CIRCLE',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan_history',
            name='DEF_60_CNT_SOCIAL_CIRCLE',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan_history',
            name='OBS_30_CNT_SOCIAL_CIRCLE',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan_history',
            name='OBS_60_CNT_SOCIAL_CIRCLE',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
