# Generated by Django 3.0.8 on 2021-01-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20210129_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='AMT_GOODS_PRICE',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
