# Generated by Django 3.0.8 on 2021-01-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20210129_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_history',
            name='AMT_GOODS_PRICE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan_history',
            name='AMT_INCOME_TOTAL',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
