# Generated by Django 3.0.8 on 2021-01-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20210129_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_history',
            name='OFFICER_ID',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
