# Generated by Django 3.0.8 on 2021-02-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_loan_history_officer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOAN_ID', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('workclass', models.CharField(blank=True, max_length=20, null=True)),
                ('fnlwgt', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=20, null=True)),
                ('education_num', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('race', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('capital_gain', models.IntegerField(blank=True, null=True)),
                ('capital_loss', models.IntegerField(blank=True, null=True)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('native_country', models.CharField(blank=True, max_length=20, null=True)),
                ('income', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
