# Generated by Django 3.0.8 on 2021-02-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_incomedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedata',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='income',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='marital_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='native_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='race',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='sex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='workclass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
