# Generated by Django 3.0.8 on 2021-01-24 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_abtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtest',
            name='parent_mlalgorithm_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_mlalgorithm_2', to='endpoints.MLAlgorithm'),
        ),
    ]
