# Generated by Django 3.0.8 on 2021-01-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_abtest_parent_mlalgorithm_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlalgorithm',
            name='parent_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_algorithm', to='endpoints.Endpoint', verbose_name='Analytics Algorithm'),
        ),
        migrations.AlterField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_algorithm_status', to='endpoints.MLAlgorithm', verbose_name='Analytics Algorithm Status'),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_request', to='endpoints.MLAlgorithm', verbose_name='Analytics request'),
        ),
    ]
