# Generated by Django 3.0.8 on 2021-01-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_auto_20210124_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='endpoints.MLAlgorithm', verbose_name='Analytics Algorithm Status'),
        ),
    ]
