# Generated by Django 3.0.8 on 2021-01-31 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_auto_20210130_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlalgorithm',
            name='parent_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.Endpoint'),
        ),
        migrations.AlterField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='endpoints.MLAlgorithm'),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.MLAlgorithm'),
        ),
    ]
