# Generated by Django 3.0.8 on 2021-01-31 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_auto_20210131_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtest',
            name='parent_mlalgorithm_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_mlalgorithm_1', to='endpoints.MLAlgorithm'),
        ),
    ]
