# Generated by Django 3.0.8 on 2021-02-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0007_auto_20210131_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=128)),
                ('client_id', models.CharField(max_length=128)),
                ('officer_id', models.CharField(max_length=128)),
                ('company_id', models.CharField(max_length=128)),
                ('income_probability', models.FloatField(blank=True, null=True)),
                ('income_color', models.CharField(blank=True, max_length=70, null=True)),
                ('income_text', models.CharField(blank=True, max_length=255, null=True)),
                ('application_probability', models.FloatField(blank=True, null=True)),
                ('application_color', models.CharField(blank=True, max_length=70, null=True)),
                ('application_text', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviouralScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=128)),
                ('client_id', models.CharField(max_length=128)),
                ('officer_id', models.CharField(max_length=128)),
                ('company_id', models.CharField(max_length=128)),
                ('income_probability', models.FloatField(blank=True, null=True)),
                ('income_color', models.CharField(blank=True, max_length=70, null=True)),
                ('income_text', models.CharField(blank=True, max_length=255, null=True)),
                ('behavioral_probability', models.FloatField(blank=True, null=True)),
                ('behavioral_color', models.CharField(blank=True, max_length=70, null=True)),
                ('behavioral_text', models.CharField(blank=True, max_length=255, null=True)),
                ('behavioral_time_to_default', models.CharField(blank=True, max_length=255, null=True)),
                ('behavioral_contact_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('behavioral_contact_schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('behavioral_message', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetentionScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=128)),
                ('client_id', models.CharField(max_length=128)),
                ('officer_id', models.CharField(max_length=128)),
                ('company_id', models.CharField(max_length=128)),
                ('income_probability', models.FloatField(blank=True, null=True)),
                ('income_color', models.CharField(blank=True, max_length=70, null=True)),
                ('income_text', models.CharField(blank=True, max_length=255, null=True)),
                ('retention_probability', models.FloatField(blank=True, null=True)),
                ('retention_color', models.CharField(blank=True, max_length=70, null=True)),
                ('retention_classification', models.CharField(blank=True, max_length=255, null=True)),
                ('retention_recommendation_process', models.CharField(blank=True, max_length=255, null=True)),
                ('retention_loan_num', models.CharField(blank=True, max_length=255, null=True)),
                ('retention_closure_date', models.CharField(blank=True, max_length=255, null=True)),
                ('retention_client_clv', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
